# Site settings
title: Richard Garner
email: rich@richgarner.net
description: > # this means to ignore newlines until "baseurl:"
  This is an amalgamation of my thoughts and experiments with software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://richgarner.net" # the base hostname & protocol for your site
twitter_username: grubstarstar
github_username:  grubstarstar

# Build settings
markdown: kramdown
