name: Richard Garner
description: This is an amalgamation of my thoughts and experiments with software development.
meta_description: "This is an amalgamation of my thoughts and experiments with software development."

aboutPage: true

markdown: kramdown
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://richgarner.net'
google_analytics: 'UA-84734980-2'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://blog.richgarner.net'
author:         'Richard Garner'
authorTwitter:  'grubstarstar'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
